---
title: "Week 4 Part 1-CI & T-tests"
author: "Nichoals Bissonnette"
date: "10/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

##1. confidene intervasl 

```{r}
otter_length <- c(38, 41, 50, 27, 32, 41, 48, 60, 43)

t.test(otter_length)
```

## T-test (1-sampple t-test)

See a claim: mean otter length is 50 inches 

```{r}
otter_test <- t.test(x= otter_length, mu= 50)
otter_test
```

## Two-sample t-test

```{r}
desert_bighorns <- c(32, 44, 18, 26, 50, 33, 42, 20)
sierra_bighorns <- c(28, 31, 40, 42, 26, 29, 31)

t.test(x= desert_bighorns, y=sierra_bighorns)
```

## End Part 1

## Part 2: Two-sample t-test 

```{r}
compact_suv <- mpg %>% 
  filter(class %in% c("compact", "suv"))
```

### Exploratory dat viz

Exploratory histograms:
```{r}
ggplot(data= compact_suv, aes(x= cty)) +
  geom_histogram()+
  facet_wrap(~class)
```
### quantile-quantile
```{r}
ggplot(data= compact_suv, aes(sample= cty)) +
  geom_qq()+
  facet_wrap(~class)
```

### Descriptive Statistics

```{r}
cars_stats<- compact_suv %>% 
  group_by(class) %>% 
  summarize(mean_city = mean(cty),
            sd_city = sd(cty),
            n= n())
```

### 2-sample t-test
Create vectors containing obsrvations for each sample (city gas Milage)

```{r}
compact_sample <- compact_suv %>% 
  filter(class== "compact") %>% 
pull(cty)

suv_sample <- compact_suv %>% 
  filter(class== "suv") %>% 
  pull(cty)

t.test(x= compact_sample, suv_sample)
```

